[package]
name = "wasmer-examples/docusaurus-wasmer-starter"
version = "0.2.1"
description = "Docusaurus Wasmer starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/docusaurus-wasmer-starter"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "build"
