[package]
name = "wasmer-examples/docusaurus-wasmer-starter"
version = "0.2.0"
description = "Wasmer Docusaurus starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/cdn-wasmer-starter"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "build"
